function [F_motor,M_motor,rpm_motor_dot] = motor_model(F,M,motor_rpm,params)

% Input parameters
% 
%   F,M: required force and moment
%
%   motor_rpm: current motor RPM
%
%   params: Quadcopter parameters
%
% Output parameters
%
%   F_motor: Actual thrust generated by Quadcopter's Motors
%
%   M_motor: Actual Moment generated by the Quadcopter's Motors
%
%   rpm_dot: Derivative of the RPM
%
%************ MOTOR MODEL ************************



ct = params.thrust_coefficient;
cq = params.moment_scale;
d = params.arm_length;
mat = [ct,   ct,    ct,  ct;...
       0,    d*ct,  0,   -d*ct;...
       -d*ct, 0,     d*ct, 0;...
       -cq,   cq,    -cq,  cq];
f = [F;M];
rpm_sqr = inv(mat) * f;
rpm_des = sqrt(rpm_sqr);
   
f_actual = mat * rpm_sqr;
F_motor = f_actual(1, :);
M_motor = f_actual(2:3, :);

km = params.motor_constant;
rpm_motor_dot = km * (rpm_des - motor_rpm);

end
